rootProject.name = 'mc121-mods'

include 'AbsentByDesign'
include 'AntiBonemeal'
include 'AutoPlant'
include 'AutoRun'
include 'BlockLayers'
include 'BlockyDoors'
include 'Cobblestoney'
include 'ColouredStuff'
include 'CreeperHeal'
include 'CustomGameRules'
include 'ElementaryOres'
include 'EnchantingRunes'
include 'FragileTorches'
include 'GardenTools'
include 'GlassCutter'
include 'HeartBalance'
include 'InventoryCrafting'
include 'LetThemGrow'
include 'MountedPearl'
include 'NoLogPunch'
include 'NutsAndFruit'
include 'OceanFloorControl'
include 'PhantomMinecart'
include 'pickybags'
include 'PlainGrinder'
include 'PotatoBread'
include 'ScaffoldingBehavior'
include 'Scraps'
include 'StonecutterLikesWood'
include 'StrongerFarmland'
include 'stupidHorseStandStill'
include 'TinyLightBulbs'
include 'UnbreakableSpawner'
include 'VeinCreeper'
include 'VillagerTools'
